# Generated by Django 3.2 on 2021-05-01 15:36

import adminpanel.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_line', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aim', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description2', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Banner/')),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now=True)),
                ('highlight_line', ckeditor.fields.RichTextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='blogs/', validators=[adminpanel.models.validate_file_size])),
                ('content', ckeditor.fields.RichTextField()),
                ('enable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/', validators=[adminpanel.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('enable', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('content_heading', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('background_image', models.ImageField(default='background.jpeg', upload_to='pages/', validators=[adminpanel.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('enable', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('content_heading', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('background_image', models.ImageField(default='background.jpeg', upload_to='pages/', validators=[adminpanel.models.validate_file_size])),
                ('sub', models.ManyToManyField(null=True, to='adminpanel.SubPage')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('enable', models.BooleanField(default=False)),
                ('photo', models.ManyToManyField(blank=True, to='adminpanel.Gallery_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.blog')),
            ],
        ),
    ]
