# Generated by Django 3.2 on 2021-05-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=130, null=True)),
                ('experience', models.IntegerField(default=0, null=True)),
                ('hard_skills', models.CharField(max_length=130, null=True)),
                ('soft_skills', models.CharField(max_length=130, null=True)),
                ('interests', models.CharField(max_length=130, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=15)),
                ('profession', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('tag_line', models.CharField(blank=True, max_length=400, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.FileField(blank=True, null=True, upload_to='id_images/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='id_images/')),
                ('profile', models.FileField(blank=True, default='default.jpg', null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
